# === RTORRENT + RUTORRENT ===
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sort-config
data:
  # Completed torrents will get moved to /downloads/<folder> based on their tracker.
  # If a torrent matches multiple trackers, then <priority> determines which location to use.
  # Higher priority numbers get used first. Edit values to fit your needs.
  sort-config.yaml: |
    plex_tv_library_id: 1
    plex_movie_library_id: 2
    plex_token: null
    plex_hostname: plex
    trackers:
      default:
        priority: 0
        folder: completed
      ubuntu.com:
        priority: 30
        folder: ubuntu
      raspberrypi.org:
        priority: 70
        folder: raspberrypi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rutorrent
spec:
  selector:
    matchLabels:
      app: rutorrent
  replicas: 1
  template:
    metadata:
      labels:
        app: rutorrent
    spec:
      volumes:
        - name: external-hdd
          hostPath:
            path: /media/hdd1
            type: Directory
        - name: rtorrent
          hostPath:
            path: /var/lib/rtorrent
            type: DirectoryOrCreate
        - name: sort-config
          configMap:
            name: sort-config
            items:
              - key: sort-config.yaml
                path: sort-config.yaml
      containers:
        - name: rutorrent
          image: pastudan/rutorrent:aa71c24
          imagePullPolicy: Always
          volumeMounts:
            - name: external-hdd
              mountPath: /downloads
            - name: rtorrent
              mountPath: /config/rtorrent/rtorrent_sess
            - name: sort-config
              mountPath: /etc/config
          ports:
            - containerPort: 5000
              name: scgi
            - containerPort: 51413
              name: bittorrent
            - containerPort: 80
              name: rutorrent-ui

---
apiVersion: v1
kind: Service
metadata:
  name: rutorrent
  labels:
    app: rutorrent
spec:
  type: NodePort
  selector:
    app: rutorrent
  ports:
    - port: 80
      nodePort: 30001
      protocol: TCP
      name: http
    - port: 5000
      nodePort: 30002
      protocol: TCP
      name: scgi
    - port: 51413
      nodePort: 30003
      protocol: TCP
      name: bittorrent

# === PLEX ===
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: plex
spec:
  selector:
    matchLabels:
      app: plex
  replicas: 1
  template:
    metadata:
      labels:
        app: plex
    spec:
      volumes:
        - name: external-hdd-tv
          hostPath:
            path: /media/hdd1/tv
            type: DirectoryOrCreate
        - name: external-hdd-movies
          hostPath:
            path: /media/hdd1/movies
            type: DirectoryOrCreate
        - name: plex-config
          hostPath:
            path: /var/lib/plex
            type: DirectoryOrCreate
      containers:
        - name: plex
          image: linuxserver/plex:latest
          imagePullPolicy: Always
          volumeMounts:
            - name: external-hdd-tv
              mountPath: /tv
            - name: external-hdd-movies
              mountPath: /movies
            - name: plex-config
              mountPath: /config
          ports:
            - containerPort: 32400
              name: plex
---
apiVersion: v1
kind: Service
metadata:
  name: plex
  labels:
    app: plex
spec:
  type: NodePort
  selector:
    app: plex
  ports:
    - port: 32400
      nodePort: 32400
      protocol: TCP
      name: plex
