---
apiVersion: v1
kind: ConfigMap
data:
  # This configures which folder a torrent's data gets moved to when complete,
  # based on the tracker hostname.
  # Values are in the format of ['folder_name', priority]
  # If a torrent has multiple trackers, the one with the lowest
  # priority will be used. Edit the values to fit your needs
  sort-config.yaml: |
    torrent.ubuntu.com: ['ubuntu_downloads', 30]
    torrent.fedoraproject.org: ['fedora_downloads', 70]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rutorrent
spec:
  selector:
    matchLabels:
      app: rutorrent
  replicas: 1
  template:
    metadata:
      labels:
        app: rutorrent
    spec:
      volumes:
        - name: external-hdd
          hostPath:
            path: /media/hdd1
      containers:
        - name: rutorrent
          image: linuxserver/rutorrent
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 500m
              memory: 256Mi
            limits:
              cpu: 1
              memory: 512Mi
          ports:
            - containerPort: 5000
              name: scgi
            - containerPort: 51413
              name: bittorrent
            - containerPort: 80
              name: rutorrent-ui
          volumeMounts:
            - name: external-hdd
              mountPath: /downloads

---
apiVersion: v1
kind: Service
metadata:
  name: rutorrent
  labels:
    app: rutorrent
spec:
  type: NodePort
  selector:
    app: rutorrent
  ports:
    - port: 80
      nodePort: 30001
      protocol: TCP
      name: http
    - port: 5000
      nodePort: 30002
      protocol: TCP
      name: scgi
    - port: 51413
      nodePort: 30003
      protocol: TCP
      name: bittorrent
