plex_tv_library_id: 1
plex_movie_library_id: 2
plex_token: null
plex_hostname: plex
# Completed torrents will get moved to /downloads/<folder> based on their tracker.
# If a torrent matches multiple trackers, then <priority> determines which location to use.
# Higher priority numbers get used first.
trackers:
  default:
    priority: 0
    folder: completed
  ubuntu.com:
    priority: 30
    folder: ubuntu
  raspberrypi.org:
    priority: 70
    folder: raspberrypi
